language: c

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1],sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

env:
  - CABALVER=1.22 GHCVER=7.10.1

install:
  - cabal install simpleirc
  - cabal install text
  - cabal install parsec
  - cabal install time
  - cabal install warp
  - cabal install blaze-builder
  - cabal install http-types
  - cabal install wai

script:
  - cabal configure
  - cabal build
