language: haskell

ghc: 7.8

install:
  - cabal install simpleirc
  - cabal install text
  - cabal install parsec
  - cabal install time
  - cabal install warp
  - cabal install blaze-builder
  - cabal install http-types
  - cabal install wai

script:
  - cabal configure
  - cabal build
